services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverDFD
    environment:
      SA_PASSWORD: "My_Passw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  
  mongodb:
    image: mongo:latest
    container_name: mongoDFD
    ports:
      - "27017:27017"